//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSpark.AzureDay.WebSite.Localization.Host.Views.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class My {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal My() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamSpark.AzureDay.WebSite.Localization.Host.Views.Profile.My", typeof(My).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участник.
        /// </summary>
        public static string Attendee {
            get {
                return ResourceManager.GetString("Attendee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ссылку.
        /// </summary>
        public static string ByLink {
            get {
                return ResourceManager.GetString("ByLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference discount code.
        /// </summary>
        public static string ConfTicketCode {
            get {
                return ResourceManager.GetString("ConfTicketCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference ticket price.
        /// </summary>
        public static string ConfTicketPrice {
            get {
                return ResourceManager.GetString("ConfTicketPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference ticket type.
        /// </summary>
        public static string ConfTicketType {
            get {
                return ResourceManager.GetString("ConfTicketType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы хотите сбросить данные в форме заказа билета, нажмите на.
        /// </summary>
        public static string DropPayment01 {
            get {
                return ResourceManager.GetString("DropPayment01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Обратите внимание, что вы не можете сбросить успешно оплаченный билет. Вы также не можете отменить оплату, если она уже прошла..
        /// </summary>
        public static string DropPayment01a {
            get {
                return ResourceManager.GetString("DropPayment01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того, чтобы прийти на AzureDay, вам не нужно печатать билет. Вместо этого вам необходимо запомнить, какие ФИО и какой адрес электронной почты вы вводили при регистрации на конференцию. Эту информацию вам необходимо будет предоставить при входе на конференцию..
        /// </summary>
        public static string HowToUseTicket {
            get {
                return ResourceManager.GetString("HowToUseTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все поля обязательны для заполнения.
        /// </summary>
        public static string isModelValid {
            get {
                return ResourceManager.GetString("isModelValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина пароля 6 символов.
        /// </summary>
        public static string isPasswordLengthValid {
            get {
                return ResourceManager.GetString("isPasswordLengthValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны совпадать.
        /// </summary>
        public static string isPasswordValid {
            get {
                return ResourceManager.GetString("isPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ticket.
        /// </summary>
        public static string MyTicket {
            get {
                return ResourceManager.GetString("MyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password again.
        /// </summary>
        public static string PasswordAgain {
            get {
                return ResourceManager.GetString("PasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оплатить картой.
        /// </summary>
        public static string PayByCard {
            get {
                return ResourceManager.GetString("PayByCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы не совершили оплату, то вы можете повторно перейти на форму оплаты используя.
        /// </summary>
        public static string PayNow {
            get {
                return ResourceManager.GetString("PayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay via LiqPay.
        /// </summary>
        public static string PayViaLiqPay {
            get {
                return ResourceManager.GetString("PayViaLiqPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal cabinet.
        /// </summary>
        public static string PersonalCabinet {
            get {
                return ResourceManager.GetString("PersonalCabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если у вас возникли вопросы по оплате, вы можете написать письмо на адрес.
        /// </summary>
        public static string Questions01 {
            get {
                return ResourceManager.GetString("Questions01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to и мы поможем вам решить все ваши вопросы..
        /// </summary>
        public static string Questions01a {
            get {
                return ResourceManager.GetString("Questions01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Большое спасибо, ваш платеж обрабатывается. Вы получите подтверждение на адрес электронной почты как только мы подтвердим оплату. Вы можете получить подтверждение о списании средств с вашей карты раньше нас, но не переживайте, мы все равно увидим вашу оплату если она была успешной..
        /// </summary>
        public static string ThankYouWait {
            get {
                return ResourceManager.GetString("ThankYouWait", resourceCulture);
            }
        }
    }
}
