//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSpark.AzureDay.WebSite.Localization.Host.Views.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Registration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Registration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamSpark.AzureDay.WebSite.Localization.Host.Views.Profile.Registration", typeof(Registration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to цена до 1го сентября.
        /// </summary>
        public static string BestBefore01 {
            get {
                return ResourceManager.GetString("BestBefore01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компания.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все поля обязательны для заполнения.
        /// </summary>
        public static string FillAllFields {
            get {
                return ResourceManager.GetString("FillAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to за 1 билет.
        /// </summary>
        public static string OneTicket {
            get {
                return ResourceManager.GetString("OneTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальная длина пароля 6 символов.
        /// </summary>
        public static string PassLength {
            get {
                return ResourceManager.GetString("PassLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароли должны совпадать.
        /// </summary>
        public static string PassMatch {
            get {
                return ResourceManager.GetString("PassMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зарегистрироваться.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на.
        /// </summary>
        public static string RegisterFor {
            get {
                return ResourceManager.GetString("RegisterFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторите пароль.
        /// </summary>
        public static string RepeatPass {
            get {
                return ResourceManager.GetString("RepeatPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личные данные, которые вы предоставите в учетной записи участника AZUREday, не будут переданы третьим лицам и будут использованы только для идентификации вас как участника конференции AZUREday..
        /// </summary>
        public static string Terms01 {
            get {
                return ResourceManager.GetString("Terms01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы соглашаетесь с этим, создавая учетную запись AZUREday..
        /// </summary>
        public static string Terms01a {
            get {
                return ResourceManager.GetString("Terms01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Билеты.
        /// </summary>
        public static string Tickets {
            get {
                return ResourceManager.GetString("Tickets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference.
        /// </summary>
        public static string TicketType01 {
            get {
                return ResourceManager.GetString("TicketType01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop.
        /// </summary>
        public static string TicketType02 {
            get {
                return ResourceManager.GetString("TicketType02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того, чтобы зарегистрироваться на AzureDay и получить возможность.
        /// </summary>
        public static string ToRegister01 {
            get {
                return ResourceManager.GetString("ToRegister01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to купить билет на конференцию.
        /// </summary>
        public static string ToRegister01a {
            get {
                return ResourceManager.GetString("ToRegister01a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , заполните форму, приведенную ниже..
        /// </summary>
        public static string ToRegister01b {
            get {
                return ResourceManager.GetString("ToRegister01b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string ToRegister02 {
            get {
                return ResourceManager.GetString("ToRegister02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не является билетом.
        /// </summary>
        public static string ToRegister02a {
            get {
                return ResourceManager.GetString("ToRegister02a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на конференцию и является бесплатной. После регистрации (создания учетной записи участника AzureDay) вам будет предложено приобрести билет..
        /// </summary>
        public static string ToRegister02b {
            get {
                return ResourceManager.GetString("ToRegister02b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи, которые создали учетную запись AzureDay, будут получать уведомления и новости конференции..
        /// </summary>
        public static string ToRegister03 {
            get {
                return ResourceManager.GetString("ToRegister03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Воспользуйтесь своей скидкой!.
        /// </summary>
        public static string UseYourDiscount {
            get {
                return ResourceManager.GetString("UseYourDiscount", resourceCulture);
            }
        }
    }
}
